#!/usr/bin/env python3
"""Generate fixed-point FIR taps for the on-device SSB modulator (src/ssb_tx.c).

Run from the repo root:  python3 tools/gen_ssb_tx_taps.py > src/ssb_tx_taps.h

Mic 64 kHz -> A: lowpass /4 -> 16 kHz -> B: lowpass /2 -> 8 kHz
-> C: complex band-pass SSB_LO..SSB_HI (keeps positive frequencies = USB, also blocks the mic DC bias)
-> D: polyphase interpolator x8 -> 64 kHz I/Q for the DAC
"""
import numpy as np

FS = 64000
A_TAPS, B_TAPS, C_TAPS = 24, 32, 64
D_PHASES, D_TAPS = 8, 12
SSB_LO, SSB_HI = 300, 2800


def lowpass(n, fc, fs, window):
    m = np.arange(n) - (n - 1) / 2
    h = 2 * fc / fs * np.sinc(2 * fc / fs * m) * window(n)
    return h / h.sum()


def quantize(h, bits):
    q = np.round(h * (1 << bits)).astype(int)
    assert np.abs(q).max() < 32768, "tap does not fit int16"
    return q


def c_array(name, q, comment):
    rows = [", ".join(f"{v:6d}" for v in q[i:i + 12]) for i in range(0, len(q), 12)]
    return f"// {comment}\nstatic const int16_t {name}[{len(q)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n"


a = lowpass(A_TAPS, 8000, FS, np.hamming)           # pass 0..3 kHz, stop >= 13 kHz
b = lowpass(B_TAPS, 4000, FS / 4, np.hamming)       # pass 0..3 kHz, stop >= 5 kHz
fs_c = FS / 8
c = lowpass(C_TAPS, (SSB_HI - SSB_LO) / 2, fs_c, np.blackman) \
    * np.exp(2j * np.pi * (SSB_LO + SSB_HI) / 2 / fs_c * np.arange(C_TAPS))
d = lowpass(D_PHASES * D_TAPS, 3900, FS, np.hamming) * D_PHASES  # images of 8 kHz start at 5 kHz
d_poly = d.reshape(D_TAPS, D_PHASES).T                           # [phase][tap]

qa, qb = quantize(a, 15), quantize(b, 15)
qcr, qci = quantize(c.real, 14), quantize(c.imag, 14)
qd = quantize(d_poly.flatten(), 15)
for q in (qa, qb, np.abs(qcr) + np.abs(qci)):
    assert 32767 * np.abs(q).sum() < 2**31, "int32 accumulator may overflow"

f = np.linspace(-4000, 4000, 1601)
hc = np.array([np.sum(c * np.exp(-2j * np.pi * fi / fs_c * np.arange(C_TAPS))) for fi in f])
db = 20 * np.log10(np.abs(hc) + 1e-12)
mirror = db[(f <= -SSB_LO) & (f >= -SSB_HI)].max()

print("// Generated by tools/gen_ssb_tx_taps.py -- do not edit by hand.")
print(f"// SSB band-pass {SSB_LO}..{SSB_HI} Hz: opposite sideband <= {mirror:.1f} dB, DC {db[np.argmin(np.abs(f))]:.1f} dB")
print("#ifndef _SSB_TX_TAPS\n#define _SSB_TX_TAPS\n#include <stdint.h>\n")
print(f"#define A_TAPS {A_TAPS}\n#define B_TAPS {B_TAPS}\n#define C_TAPS {C_TAPS}")
print(f"#define D_PHASES {D_PHASES}\n#define D_TAPS {D_TAPS}\n")
print(c_array("taps_a", qa, "A: 64 kHz lowpass before /4, Q15"))
print(c_array("taps_b", qb, "B: 16 kHz lowpass before /2, Q15"))
print(c_array("taps_c_re", qcr, "C: 8 kHz complex band-pass, real part, Q14"))
print(c_array("taps_c_im", qci, "C: imaginary part, Q14 (negated for LSB)"))
print(c_array("taps_d", qd, f"D: x{D_PHASES} interpolator, {D_PHASES} phases x {D_TAPS} taps, [phase][tap], Q15"))
print("#endif")
