#!/usr/bin/env python3
"""Generate the fixed-point polyphase resampler taps for src/audio.c.

Run from the repo root:  python3 tools/gen_audio_taps.py > src/audio_taps.h

Resamples the ADC rate (72 MHz / 1125 = 64000 Hz) to the I2S rate (72 MHz / 1472 = 48913 Hz).
The prototype lowpass keeps the audio band and suppresses what would alias above I2S Nyquist.
"""
import numpy as np

FS_IN = 64000
R_PHASES, R_TAPS = 64, 16
CUTOFF = 12000  # voice band; with 16 taps the stopband starts below ~19 kHz, so nothing aliases past I2S Nyquist (24456 Hz)

n = R_PHASES * R_TAPS
m = np.arange(n) - (n - 1) / 2
fs_proto = FS_IN * R_PHASES
h = 2 * CUTOFF / fs_proto * np.sinc(2 * CUTOFF / fs_proto * m) * np.hamming(n)
h = h / h.sum() * R_PHASES  # each phase has ~unity DC gain

# polyphase layout: phase p, tap k -> h[k * R_PHASES + p], stored as [p][k]
poly = h.reshape(R_TAPS, R_PHASES).T
q = np.round(poly * (1 << 15)).astype(int)
assert np.abs(q).max() < 32768, "tap does not fit int16"
# int32 accumulator is safe for |sample| <= 32767
assert all(32767 * np.abs(q[p]).sum() < 2**31 for p in range(R_PHASES))

flat = q.flatten()
rows = [", ".join(f"{v:6d}" for v in flat[i:i + 16]) for i in range(0, len(flat), 16)]
print("// Generated by tools/gen_audio_taps.py -- do not edit by hand.")
print("#ifndef _AUDIO_TAPS\n#define _AUDIO_TAPS\n#include <stdint.h>\n")
print(f"#define R_PHASES {R_PHASES}\n#define R_TAPS {R_TAPS}\n")
print(f"// 64 kHz -> I2S resampler lowpass ({CUTOFF} Hz), {R_PHASES} phases x {R_TAPS} taps, [phase][tap], Q15")
print(f"static const int16_t taps_r[{len(flat)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n")
print("#endif")
