#!/usr/bin/env python3
"""Generate the constant tables for the TFT spectrum/waterfall (src/spectrum.c).

Run from the repo root:  python3 tools/gen_spectrum_tables.py > inc/spectrum_tables.h

Tables live in flash (const): they are read once per sample/bin per frame, not per tap, so the flash wait
states don't matter here and the RAM is kept for buffers.
"""
import numpy as np

N = 256          # FFT size
PALETTE = 64     # waterfall colours


def c_array(ctype, name, values, per_row=12):
    v = [int(x) for x in np.asarray(values).flatten()]
    rows = [", ".join(f"{x:6d}" for x in v[i:i + per_row]) for i in range(0, len(v), per_row)]
    return f"static const {ctype} {name}[{len(v)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n"


window = np.round(np.hanning(N) * 32767)                      # Q15 Hann
k = np.arange(N // 2)
tw_cos = np.round(np.cos(2 * np.pi * k / N) * 32767)          # forward FFT twiddle = cos - j*sin
tw_sin = np.round(np.sin(2 * np.pi * k / N) * 32767)
bitrev = [int(f"{i:08b}"[::-1], 2) for i in range(N)]

# Waterfall palette: black -> blue -> cyan -> green -> yellow -> red -> white, 6-bit channels (ILI9488 RGB666)
stops = [(0, 0, 0), (0, 0, 40), (0, 40, 63), (0, 63, 20), (63, 63, 0), (63, 0, 0), (63, 63, 63)]
pos = np.linspace(0, 1, len(stops))
t = np.linspace(0, 1, PALETTE)
pal = np.stack([np.interp(t, pos, [s[c] for s in stops]) for c in range(3)], axis=1)
pal = (np.round(pal).astype(int) << 2)                         # 6-bit value in the top bits of each byte

print("// Generated by tools/gen_spectrum_tables.py -- do not edit by hand.")
print("#ifndef _SPECTRUM_TABLES\n#define _SPECTRUM_TABLES\n#include <stdint.h>\n")
print(f"#define FFT_N {N}\n#define FFT_LOG2N {N.bit_length() - 1}\n#define WF_PALETTE {PALETTE}\n")
print("// Hann window, Q15")
print(c_array("int16_t", "fft_window", window))
print("// Twiddles W^k = cos(2*pi*k/N) - j*sin(2*pi*k/N), Q15")
print(c_array("int16_t", "fft_cos", tw_cos))
print(c_array("int16_t", "fft_sin", tw_sin))
print("// Bit-reversed index: samples are stored in this order so the in-place FFT needs no reorder pass")
print(c_array("uint8_t", "fft_bitrev", bitrev, per_row=16))
print("// Waterfall palette, RGB666 bytes (R, G, B)")
print(c_array("uint8_t", "wf_palette", pal, per_row=12))
print("#endif")
