#!/usr/bin/env python3
"""Generate fixed-point FIR taps for the on-device SSB modulator (src/ssb_tx.c) and demodulator (src/ssb_rx.c).

Run from the repo root:  python3 tools/gen_ssb_taps.py > inc/ssb_taps.h

The tables are plain (non-const) arrays so they are copied to RAM at startup: reading taps from flash
costs 2 wait states each at 72 MHz. src/ssb_taps.c defines them by including this header with SSB_TAPS_DEFINE.

Shared:  64 kHz -> A: lowpass /4 -> 16 kHz -> B: lowpass /2 -> 8 kHz
         -> C: complex band-pass SSB_LO..SSB_HI (positive frequencies only = USB; also blocks DC)
TX:      mic (real) through A, B, C -> analytic I/Q -> D: polyphase interpolator x8 -> 64 kHz DAC
RX:      ADC I/Q (complex) through A, B, C, real part = audio -> R: polyphase 8 kHz -> I2S 48913 Hz
"""
import numpy as np

FS = 64000
FS_BB = FS / 8
A_TAPS, B_TAPS, C_TAPS = 24, 32, 64
D_PHASES, D_TAPS = 8, 12
R_PHASES, R_TAPS = 64, 16
SSB_LO, SSB_HI = 300, 2800


def lowpass(n, fc, fs, window):
    m = np.arange(n) - (n - 1) / 2
    h = 2 * fc / fs * np.sinc(2 * fc / fs * m) * window(n)
    return h / h.sum()


def polyphase(h, phases, taps):
    return (h * phases).reshape(taps, phases).T  # [phase][tap], each phase ~unity DC gain


def quantize(h, bits):
    q = np.round(np.asarray(h) * (1 << bits)).astype(int)
    assert np.abs(q).max() < 32768, "tap does not fit int16"
    return q


def c_array(name, q, comment):
    q = q.flatten()
    assert len(q) % 4 == 0, "fir_dot() is unrolled by 4"
    rows = [", ".join(f"{v:6d}" for v in q[i:i + 12]) for i in range(0, len(q), 12)]
    return (f"// {comment}\n#ifdef SSB_TAPS_DEFINE\nint16_t {name}[{len(q)}] = {{\n    " + ",\n    ".join(rows)
            + f"\n}};\n#else\nextern int16_t {name}[{len(q)}];\n#endif\n")


a = lowpass(A_TAPS, 8000, FS, np.hamming)       # pass 0..3 kHz, stop >= 13 kHz (aliases of /4)
b = lowpass(B_TAPS, 4000, FS / 4, np.hamming)   # pass 0..3 kHz, stop >= 5 kHz (aliases of /2)
c = lowpass(C_TAPS, (SSB_HI - SSB_LO) / 2, FS_BB, np.blackman) \
    * np.exp(2j * np.pi * (SSB_LO + SSB_HI) / 2 / FS_BB * np.arange(C_TAPS))
d = polyphase(lowpass(D_PHASES * D_TAPS, 3900, FS, np.hamming), D_PHASES, D_TAPS)                 # 8 kHz images from 5.2 kHz
r = polyphase(lowpass(R_PHASES * R_TAPS, 3600, FS_BB * R_PHASES, np.hamming), R_PHASES, R_TAPS)  # same, towards I2S

qa, qb = quantize(a, 15), quantize(b, 15)
qcr, qci = quantize(c.real, 14), quantize(c.imag, 14)
qd, qr = quantize(d, 15), quantize(r, 15)
# int32 accumulators are safe for |sample| <= 32767 when sum|tap| * 32767 < 2^31
for q in (qa, qb, np.abs(qcr) + np.abs(qci), *qd, *qr):
    assert 32767 * np.abs(q).sum() < 2**31, "int32 accumulator may overflow"

f = np.linspace(-4000, 4000, 1601)
hc = np.array([np.sum(c * np.exp(-2j * np.pi * fi / FS_BB * np.arange(C_TAPS))) for fi in f])
db = 20 * np.log10(np.abs(hc) + 1e-12)
mirror = db[(f <= -SSB_LO) & (f >= -SSB_HI)].max()

print("// Generated by tools/gen_ssb_taps.py -- do not edit by hand.")
print(f"// SSB band-pass {SSB_LO}..{SSB_HI} Hz: opposite sideband <= {mirror:.1f} dB, DC {db[np.argmin(np.abs(f))]:.1f} dB")
print("#ifndef _SSB_TAPS\n#define _SSB_TAPS\n#include <stdint.h>\n")
print(f"#define A_TAPS {A_TAPS}\n#define B_TAPS {B_TAPS}\n#define C_TAPS {C_TAPS}")
print(f"#define D_PHASES {D_PHASES}\n#define D_TAPS {D_TAPS}")
print(f"#define R_PHASES {R_PHASES}\n#define R_TAPS {R_TAPS}\n")
print(c_array("taps_a", qa, "A: 64 kHz lowpass before /4, Q15"))
print(c_array("taps_b", qb, "B: 16 kHz lowpass before /2, Q15"))
print(c_array("taps_c_re", qcr, f"C: 8 kHz complex band-pass {SSB_LO}..{SSB_HI} Hz, real part, Q14"))
print(c_array("taps_c_im", qci, "C: imaginary part, Q14 (negated for LSB)"))
print(c_array("taps_d", qd, f"D (TX): x{D_PHASES} interpolator 8 -> 64 kHz, {D_PHASES} phases x {D_TAPS} taps, [phase][tap], Q15"))
print(c_array("taps_r", qr, f"R (RX): 8 kHz -> I2S resampler, {R_PHASES} phases x {R_TAPS} taps, [phase][tap], Q15"))
print("#endif")
